project:
  type: website

website:
  title: "Investigación No Experimental y Estadística"
  sidebar:
    style: "floating"
    search: true
    contents: auto
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
